
Vagrant.configure("2") do |config|
  
  config.vm.box = "sbeliakou/centos"
  config.vm.define "master" do |test|
	test.vm.hostname="master-node"
	test.vm.network :private_network, ip: "192.168.56.20"
	test.vm.provider "virtualbox" do |vb|
		vb.memory=2048
	end
	#test.vm.provision :shell, path: "java.sh"
  end
  config.vm.define "worker" do |test|
	test.vm.hostname="worker-node"
	test.vm.network :private_network, ip: "192.168.56.21"
	test.vm.provider "virtualbox" do |vb|
		vb.memory=1024
	end
end
end
