- name: Deploy tomcat service
  template:
    src: tomcat.j2
    dest: /etc/systemd/system/tomcat.service
  become: yes
  
- name: copy context.xml
  copy:
    src: context.xml
    dest: "{{tomcat_home}}/webapps/manager/META-INF/context.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: yes

- name: create Catalina dir
  file:
    path: "{{tomcat_home}}/conf/Catalina/localhost"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: yes
  
- name: tune1
  copy:
    src: manager.xml
    dest: "{{tomcat_home}}/conf/Catalina/localhost"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: yes
  

- name: tune2
  template:
    src: tomcat-users.j2
    dest: "{{tomcat_home}}/conf/tomcat-users.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: yes
  notify: tom_tune

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers