- name: get the tomcat gen
  shell: echo "{{tomcat}}" | cut -d'.' -f1
  register: tom_gen 

- name: download tomcat
  get_url:
    url: "http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-{{tom_gen.stdout}}/v{{tomcat}}/bin/apache-tomcat-{{tomcat}}.zip"
    dest: /opt
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  register: tmp
  become: yes

- name: Decompress tomcat
  unarchive:
    src: "{{tmp.dest}}"
    dest: /opt
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    remote_src: yes
  become: yes
  
- name: Get the folder name
  shell: echo "{{ tmp.dest }}" |  cut -d'.' -f1-3
  register: tmp

- debug: msg="{{tmp.stdout}}"

- name: change owner and mode
  file:
    path: "{{tmp.stdout}}/bin/"
    recurse: yes
    mode: 0755
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: yes

- name: create link
  file:
    src: "{{tmp.stdout}}"
    dest: /opt/tomcat
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    state: link
  become: yes