- debug: msg="{{tmp.stdout}}"

- name: create link
  file:
    src: "/opt/{{tmp.stdout}}"
    dest: "{{nexus_home}}"
    owner: "{{nexus_user}}"
    group: "{{nexus_group}}"
    state: link
  become: yes
  
- name: Change workfolders owner
  file:
    path: "{{item}}"
    owner: "{{nexus_user}}"
    group: "{{nexus_group}}"
    recurse: yes
  with_items:
    - "/opt/{{tmp.stdout}}"
    - /opt/sonatype-work  
  become: yes

- name: Deploy service file
  template:
    src: nexus.j2
    dest: /etc/systemd/system/nexus.service
    owner: "{{nexus_user}}"
    group: "{{nexus_group}}"
  become: yes
  notify: nex_start