- name: get src loc
  shell: echo "{{tmp.dest}}" | cut -d'.' -f1-3
  register: tmp

- name: Create sonar link
  file:
    src: "{{tmp.stdout}}"
    dest: "{{sonar_home}}"
    owner: "{{sonar_user}}"
    group: "{{sonar_group}}"
    state: link
  become: yes

- name: Copy custom sonar props
  template:
    src: sonar.properties.j2
    dest: "{{sonar_home}}/conf/sonar.properties"
    owner: "{{sonar_user}}"
    group: "{{sonar_group}}"
  become: yes

- name: Sonar service
  template:
    src: sonar.j2
    dest: /etc/systemd/system/sonar.service
  become: yes
  notify: "start sonar"

  