- name: Create artifact folder
  file:
    path: "{{jen_home}}/artifacts"
    state: directory
    owner: "{{jen_user}}"
    group: "{{jen_group}}"
  become: yes

- name: Deploy jenkins.service
  template:
    src: jenkins.j2
    dest: /etc/systemd/system/jenkins.service
  become: yes
  notify: start jenkins

- name: Directory for maven settings
  file:
    path: /home/jenkins/.m2
    state: directory
    owner: "{{jen_user}}"
  become: yes

- name: Copy settings for maven (nexus connectivity)
  template:
    src: settings.j2
    dest: /home/jenkins/.m2/settings.xml
    owner: "{{jen_user}}"
  become: yes
