- name: Create artifact folder
  file:
    path: /opt/jenkins/artifacts
    state: directory
    owner: jenkins
    group: jenkins
  become: yes

- name: Deploy jenkins.service
  copy:
    src: jenkins.service
    dest: /etc/systemd/system/
  become: yes
  notify: start jenkins

- name: Directory for maven settings
  file:
    path: /home/jenkins/.m2
    state: directory
    owner: jenkins
  become: yes

- name: Copy settings for maven (nexus connectivity)
  copy:
    src: settings.xml
    dest: /home/jenkins/.m2/
    owner: jenkins
  become: yes
